### ISSUE TITLE
Listing empty vault seems fishy

### ISSUE THREAD

**Issue by samthebest** [sniptt-official/snip-cli#7]
```
samsavage@CVX-0032:/tmp snip ls --vault datauniverse_vault
✔ Fetching existing vault memberships
✔ Fetching vault secrets
Secret Name Owner
```

It looks like the vault contains 1 secret called `Secret Name Owner` but I don't think that is the intension.

If the vault is empty, no text should be output, or it should say "vault empty" or something.

**Comment by rogerthebest** [comment]
@samthebest This has been fixed by https://github.com/sniptt-official/snip-cli/commit/4aab5fa0566b4e349f2ef1b7e6f70a5fd96ce494#diff-ddcff290420a78a866008011f4c62b1a4ce4aedb62a6e522c6b6f9daba67f3f8R23-R27 and released in [v0.0.46](https://github.com/sniptt-official/snip-cli/releases/tag/v0.0.46).

Upgrade to this version by running `brew upgrade sniptt-official/snip/snip`.

Expected output:

```sh
$ snip ls --vault test
✔ Fetching existing vault memberships
✔ Fetching vault secrets
Vault is empty
```
